eval:
  homeConfigurations: true
  nixosConfigurations: true
  packages: true

  extra:
    devShells:
      x86_64-linux:
        default:

build:
  homeConfigurations: true
  nixosConfigurations: true
  packages: true

  extra:
    devShells:
      x86_64-linux:
        default:
