creation_rules:
  - key_groups:
      - age:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGdXzGIGojiTBR6ihaiWkD907bjPxQtT9X5MS+aEJPQ3 root@ari
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEvzKJsGyNVi2k6pQVS3Qvi3zm8vVkbVALNo/lKe+VQ root@desk
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOoDSU6wnEtGjwGVfH53Idjo7LhzfLxpmhQxvwLUUx60 jess@desk
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICk0WIlzz2d+BklFE18Wu0/oAX7T7dC6M9+anqvXlY1c jess@jess-laptop
        pgp:
          - 80923BD1ECD0E436671DC8E9BA3350686C918606
    path_regex: secrets/nixos.yaml
  - key_groups:
      - age:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEvzKJsGyNVi2k6pQVS3Qvi3zm8vVkbVALNo/lKe+VQ root@desk
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwkykAOaKE67Xe4hqJVHTjIm6EwBWqFGj7oqLWQjxKI ci
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJoez2W1Txg4lD4DKeiZa2jawwbMlffuq2vJweUiwia root@jess-laptop
        pgp:
          - 80923BD1ECD0E436671DC8E9BA3350686C918606
    path_regex: secrets/buildtime.yaml
note: This file was generated by tools/generate-sops-yaml
