apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: apps
spec:
  project: apps
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          ingressClassResource:
            default: true
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
