apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
data:
  atticd.yaml: |
    listen = "[::]:8080"

    [chunking]
    avg-size = 65536
    max-size = 262144
    min-size = 16384
    nar-size-threshold = 65536

    [database]
    url = "postgresql://attic@ari/attic"
    
    [storage]
    bucket = "nix-cache-b5eea907c395"
    endpoint = "https://nix-cache-b5eea907c395.s3.us-west-002.backblazeb2.com"
    region = "us-west-002"
    type = "s3"
