apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: radicale
  labels:
    app: radicale
data:
  config: |-
    [server]
    hosts = 0.0.0.0:5232

    [storage]
    filesystem_folder = /data/collections
