apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: apps
  sources:
    - chart: gha-runner-scale-set-controller
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.10.1
      helm:
        releaseName: gha-runner-scale-set-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-system
  syncPolicy:
    syncOptions:
      # https://github.com/argoproj/argo-cd/issues/820
      - Replace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
