apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: apps
spec:
  project: apps
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
    helm:
      releaseName: longhorn
      valuesObject:
        # https://github.com/longhorn/longhorn/issues/6946
        preUpgradeChecker:
          jobEnabled: false
        ingress:
          enabled: true
          host: longhorn.k8s.jessie.cafe
          tls: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production

            # mtls
            nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
            nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
            nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
            # FIXME: part of declarative secret management
            nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
