# Broken, see: https://github.com/zhaofengli/attic/issues/219

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attic
  namespace: apps
spec:
  project: apps
  source:
    repoURL: "https://github.com/ttrssreal/jix"
    path: "k8s/attic/resources"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: attic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
