{ inputs, ... }:
{
  flake.jix.sops-yaml =
    let
      inherit (inputs.nixpkgs) lib;

      pgp = {
        # https://jessie.cafe/gpg.asc
        jess = "80923BD1ECD0E436671DC8E9BA3350686C918606";
      };

      ssh = lib.mapAttrs (_: key: lib.trim (lib.readFile key)) {
        ari = ../nixos/ari/hostKey.pub;
      };
    in
    {
      note = "This file was generated by tools/generate-sops-yaml";
      creation_rules = [
        {
          path_regex = "secrets/nixos.yaml";
          key_groups = [
            {
              pgp = [
                pgp.jess
              ];
              age = [
                ssh.ari
              ];
            }
          ];
        }
      ];
    };
}
