{ inputs, ... }:
{
  flake.jix.sops-yaml =
    let
      inherit (inputs.nixpkgs) lib;

      pgp = {
        # https://jessie.cafe/gpg.asc
        jess = "80923BD1ECD0E436671DC8E9BA3350686C918606";
        # laptop subkey
        jess-laptop = "3B2B3B753452DC1AD25DED1C447A0766118B05B9";
      };

      ssh = lib.mapAttrs (_: key: lib.trim (lib.readFile key)) {
        ari = ../nixos/ari/hostKey.pub;
        desk = ../nixos/desk/hostKey.pub;
        jess-laptop = ../nixos/jess-laptop/hostKey.pub;
        "jess@desk" = ../home/jess/desk/homeKey.pub;
        "jess@jess-laptop" = ../home/jess/jess-laptop/homeKey.pub;
        "jess@laptop" = ../home/jess/laptop/homeKey.pub;
        laptop = ../nixos/laptop/hostKey.pub;
        ci = ../.github/ci.pub;
      };
    in
    {
      note = "This file was generated by tools/generate-sops-yaml";
      creation_rules = [
        {
          path_regex = "secrets/nixos.yaml";
          key_groups = [
            {
              pgp = [
                pgp.jess
                pgp.jess-laptop
              ];
              age = [
                ssh.ari
                ssh.desk
                ssh."jess@desk"
                ssh."jess@jess-laptop"
                ssh.jess-laptop
                ssh.laptop
                ssh."jess@laptop"
              ];
            }
          ];
        }
        {
          path_regex = "secrets/buildtime.yaml";
          key_groups = [
            {
              pgp = [
                pgp.jess
                pgp.jess-laptop
              ];
              age = [
                ssh.desk
                ssh.ci
                ssh.jess-laptop
                ssh.laptop
              ];
            }
          ];
        }
      ];
    };
}
