apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible-analytics-dashboard
  namespace: plausible-analytics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

    # mtls
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    # FIXME: part of declarative secret management
    nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
spec:
  ingressClassName: nginx
  rules:
    - host: dashboard.analytics.jessie.cafe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible-analytics
                port:
                  name: http
  tls:
    - hosts:
      - dashboard.analytics.jessie.cafe
      secretName: plausible-analytics-dashboard-cert
