
name: Build and cache all the things

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [cluster-runner]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Magic
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ari:8080
          cache: nix-cache
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"

      - name: Build
        run: om ci run -- --refresh --sandbox -j auto --cores 0
