
name: Build and cache all the things

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # https://crontab.guru/#0_13_*_*_tue
    - cron: "0 13 * * tue"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    environment: build

    strategy:
      matrix:
        runner: [nix]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Magic
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Setup Attic cache
        if: github.event_name != 'pull_request'
        uses: ryanccn/attic-action@v0
        with:
          endpoint: http://ari:8080
          cache: nix-cache
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"

      - name: Build
        run: om ci run -- --refresh --sandbox -j auto --cores 0
